requires 'JSON';
requires 'Starman';
requires 'Template';
requires 'DateTime';
requires 'DBIx::Class';
requires 'DBIx::Class::Schema::Loader';
requires 'DateTime::Format::SQLite';
requires 'Dancer';
requires 'Dancer::Plugin::DBIC';
requires 'Test::WWW::Mechanize::Dancer';
requires 'Dancer::Plugin::Passphrase', '>= 1.00';
requires 'Dancer::Plugin::CDN';
requires 'HTTP::CDN';
requires 'CSS::Minifier::XS';
requires 'JavaScript::Minifier::XS';
requires 'MIME::Lite';
